# Cargo config file

# Environment variables
[env]

## Secrets
# Contraseñas para desarrollo en localhost

#SERVICE_DB_URL = "postgres://app_user:dev_only_pwd@localhost/app_db"
SERVICE_DB_URL = "postgres://postgres:root@db:5432/gestor_documental"

SERVICE_PWD_KEY = "VjPT_xyBpjbXlA8Yb7Tdz9W_Pwv_iwyZXxwdqgouL6LiX3n1UakkB8to0QmLiqTjbd5mkCphI9qeYQnKETnZMw"

SERVICE_TOKEN_KEY = "DHaaUOeyjFB8OqA7LoAI4pbvIn0INpvUo9K-Fkyb188BkZasmk7I_lYL4thL5jg8iYdOUnRgpYQ7uD-l_qjypQ"

SERVICE_TOKEN_DURATION_SEC = "1800" # 30 min

# Scope down traceing, to filter out external lib tracing
RUST_LOG="rust_web_app=debug"
SERVICE_WEB_FOLDER="web-folder/"
