name: Check Commit Message Format

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get commit messages
      run: |
        commits=$(jq -r '.commits[] | .message' < "$GITHUB_EVENT_PATH")
        echo "$commits" > commit_messages.txt
      shell: bash

    - name: Check commit messages
      run: |
        invalid_commits=$(grep -Ev '^(FEAT|FIX): .+' commit_messages.txt)
        if [ -n "$invalid_commits" ]; then
          echo "Invalid commit messages found:"
          echo "$invalid_commits"
          exit 1
        fi
      shell: bash

