name: Enforce Commit Message Format

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit messages
      run: |
        commits=$(git log --format=%s --no-merges ${{ github.event.before }}..${{ github.sha }})
        
        echo "Checking commit messages..."
        
        invalid_commit_found=false

        for commit in $commits; do
          if ! [[ "$commit" =~ ^(FEAT|FIX):\ .* ]]; then
            echo "Invalid commit message: $commit"
            invalid_commit_found=true
          fi
        done

        if $invalid_commit_found; then
          echo "One or more commits do not follow the required format (FEAT: *Commit message* or FIX: *Commit message*)."
          exit 1
        else
          echo "All commit messages are valid."
        fi

