name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Synchronize files to the server
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ root@${{ secrets.HOST }}:/root/backend/

          # Install dependencies
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "sudo apt-get update && sudo apt-get install -y build-essential"

          # Install Rust
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env"

          # Build the project
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "cd /root/backend && source $HOME/.cargo/env && cargo build --release"

          # Test the project
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "cd /root/backend && source $HOME/.cargo/env && cargo test --release"

          # Restart the service
          ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "sudo systemctl restart rust_backend.service"
