name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Synchronize files to the server
          rsync -avz --delete ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/${{ secrets.USERNAME }}/backend/

          # Install dependencies
          apt-get update && apt-get install -y build-essential

          # Install Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

          # Build the project
          cd /root/backend && source $HOME/.cargo/env && cargo build --release

          # Test the project
          cd /root/backend && source $HOME/.cargo/env && cargo test --release

          # Restart the service
          # sudo systemctl restart rust_backend.service
