name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no root@184.168.64.136 "echo 'SSH connection successful'"

    - name: Copy files to the server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ root@184.168.64.136:/root/backend/

    - name: Install dependencies on server
      run: |
        ssh -o StrictHostKeyChecking=no root@184.168.64.136 "sudo apt-get update && sudo apt-get install -y build-essential"

    - name: Install Rust on server
      run: |
        ssh -o StrictHostKeyChecking=no root@184.168.64.136 "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env"

    - name: Build project on server
      run: |
        ssh -o StrictHostKeyChecking=no root@184.168.64.136 "cd /root/backend && source $HOME/.cargo/env && cargo build --release"

    - name: Test project on server
      run: |
        ssh -o StrictHostKeyChecking=no root@184.168.64.136 "cd /root/backend && source $HOME/.cargo/env && cargo test --release"
