name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Load variables
      run: |
        touch .env
        echo "${{ secrets.ENV_VARIABLES }}" > .env

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env

    - name: Build
      run: |
        source $HOME/.cargo/env
        cargo build

    - name: Test
      run: |
        source $HOME/.cargo/env
        cargo test
      
